# docker-compose.yaml
  version: '3.8'
  services:
    jenkins:
      image: jenkins/jenkins:lts-jdk11
      privileged: true
      user: root
      ports:
        - 8080:8080
      volumes:
        - /tmp/jenkins_configuration:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock